### ISSUE TITLE
Look into including MONO-TOUCH Chipmunk bindings

### ISSUE THREAD

**Issue by kjpou1** [mono/cocos2d-xna#2]

**Comment by kjpou1** [comment]
One problem with this is that Chipmunk does not include native interface for all platforms.

**Comment by kjpou1** [comment]
Ok looked into this yesterday but the current chipmunk bindings for monotouch-bindings are not building against the current version of Chipmunk.

**Comment by StephaneDelcroix** [comment]
First, don't underestimate the communication costs between a managed cocos and a native chipmunk. I tried it the other way around (managed physics engine, native cocos) and this had a major performance hit: http://stackoverflow.com/questions/14985336/reducing-the-cost-of-native-managed-interactions-in-monotouch

The chipmunk bindings in mt-bindings were made for 6.1.1 (not yet updated to 6.1.4), but anyway, you're right the project doesn't build anymore. I suspect this is caused by the latest update of Xcode...

I'll try to fix that as soon as I find some time to

**Comment by totallyeviljake** [comment]
:) that's why we are converting chipmunk to C# as well - to see if the marshaling layer costs too much.

**Comment by StephaneDelcroix** [comment]
Oh, I had a partial port working at some point

**Comment by totallyeviljake** [comment]
that's funny. It seems that many people have had partial ports of box2d and chipmunk spread around the net. I am about 30% done with my port - mostly been busy with optimizing box2d.

**Comment by kjpou1** [comment]
@StephaneDelcroix  Been on vacation and will start looking at it.  Thanks
